// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVmmZ529PnfX069O46UKApjQBSQJtUUbk',
    appId: '1:55577073376:web:5eae49806b41fc95682285',
    messagingSenderId: '55577073376',
    projectId: 'navigation-2-a3783',
    authDomain: 'navigation-2-a3783.firebaseapp.com',
    databaseURL: 'https://navigation-2-a3783-default-rtdb.firebaseio.com',
    storageBucket: 'navigation-2-a3783.appspot.com',
    measurementId: 'G-EKX3E55M7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2N7RBf4B6Vwh_WsJzEzVE86fumtqWNYs',
    appId: '1:55577073376:android:b38badc7a4e21da3682285',
    messagingSenderId: '55577073376',
    projectId: 'navigation-2-a3783',
    databaseURL: 'https://navigation-2-a3783-default-rtdb.firebaseio.com',
    storageBucket: 'navigation-2-a3783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQyMKfIeym4MLXJMD_-ymEBMx8qqrr6T0',
    appId: '1:55577073376:ios:f3f92af41aed13c0682285',
    messagingSenderId: '55577073376',
    projectId: 'navigation-2-a3783',
    databaseURL: 'https://navigation-2-a3783-default-rtdb.firebaseio.com',
    storageBucket: 'navigation-2-a3783.appspot.com',
    iosClientId: '55577073376-vctjnkfk76duki8afpfndbb4043o6emm.apps.googleusercontent.com',
    iosBundleId: 'com.example.navigatorAssignment9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQyMKfIeym4MLXJMD_-ymEBMx8qqrr6T0',
    appId: '1:55577073376:ios:f3f92af41aed13c0682285',
    messagingSenderId: '55577073376',
    projectId: 'navigation-2-a3783',
    databaseURL: 'https://navigation-2-a3783-default-rtdb.firebaseio.com',
    storageBucket: 'navigation-2-a3783.appspot.com',
    iosClientId: '55577073376-vctjnkfk76duki8afpfndbb4043o6emm.apps.googleusercontent.com',
    iosBundleId: 'com.example.navigatorAssignment9',
  );
}
